CREATE BITMAP INDEX S_NATIONKEY_IDX ON ${schema}SUPPLIER${org} (S_NATIONKEY)
;
CREATE BITMAP INDEX PS_SUPPKEY_IDX ON ${schema}PARTSUPP${org} (PS_SUPPKEY)
;
CREATE BITMAP INDEX L_ORDERKEY_IDX ON ${schema}LINEITEM${org} (L_ORDERKEY)
;
CREATE BITMAP INDEX L_PARTKEY_IDX ON ${schema}LINEITEM${org} (L_PARTKEY)
;
CREATE BITMAP INDEX L_SHIPDATE_CLUIDX ON ${schema}LINEITEM${org} (L_SHIPDATE)
;
CREATE BITMAP INDEX L_RECEIPTDATE_IDX ON ${schema}LINEITEM${org} (L_RECEIPTDATE)
;
CREATE BITMAP INDEX L_SUPPKEY_IDX ON ${schema}LINEITEM${org} (L_SUPPKEY)
;
CREATE BITMAP INDEX N_REGIONKEY_IDX ON ${schema}NATION${org} (N_REGIONKEY)
;
CREATE BITMAP INDEX O_ORDERDATE_CLUIDX ON ${schema}ORDERS${org} (O_ORDERDATE)
;
CREATE BITMAP INDEX O_CUSTKEY_IDX ON ${schema}ORDERS${org} (O_CUSTKEY)
;
CREATE BITMAP INDEX C_NATIONKEY_IDX ON ${schema}CUSTOMER${org} (C_NATIONKEY)
;
