CREATE BITMAP INDEX FIELD1_IDX ON ${schema}DASHLOAD (FIELD1)
;
CREATE BITMAP INDEX FIELD2_IDX ON ${schema}DASHLOAD (FIELD2)
;
CREATE BITMAP INDEX FIELD3_IDX ON ${schema}DASHLOAD (FIELD3)
;
CREATE BITMAP INDEX FIELD4_IDX ON ${schema}DASHLOAD (FIELD4)
;
CREATE BITMAP INDEX FIELD5_IDX ON ${schema}DASHLOAD (FIELD5)
;
CREATE BITMAP INDEX FIELD6_IDX ON ${schema}DASHLOAD (FIELD6)
;
CREATE BITMAP INDEX FIELD7_IDX ON ${schema}DASHLOAD (FIELD7)
;
CREATE BITMAP INDEX FIELD8_IDX ON ${schema}DASHLOAD (FIELD8)
;
CREATE BITMAP INDEX FIELD9_IDX ON ${schema}DASHLOAD (FIELD9)
;
