CREATE TABLE ${schema}DASHLOAD${org}  ( 
	field1		BINARY WITH STORAGETYPE = COLUMNAR,
	field2		MONEY WITH STORAGETYPE = COLUMNAR,
	field3		DATE WITH STORAGETYPE = COLUMNAR,
	field4		DECIMAL WITH STORAGETYPE = COLUMNAR,
	field5		DOUBLE WITH STORAGETYPE = COLUMNAR,
	field6		INTEGER WITH STORAGETYPE = COLUMNAR,
	field7		NUMERIC WITH STORAGETYPE = COLUMNAR,
	field8		VARCHAR(30) WITH STORAGETYPE = COLUMNAR,
	field9		TIMESTAMP WITH STORAGETYPE = COLUMNAR ${shardkey})
;

