CREATE BITMAP INDEX FIELD1_IDX ON ${schema}DASHLOAD${org} (FIELD1)
;
CREATE BITMAP INDEX FIELD2_IDX ON ${schema}DASHLOAD${org} (FIELD2)
;
CREATE BITMAP INDEX FIELD3_IDX ON ${schema}DASHLOAD${org} (FIELD3)
;
CREATE BITMAP INDEX FIELD4_IDX ON ${schema}DASHLOAD${org} (FIELD4)
;
CREATE BITMAP INDEX FIELD5_IDX ON ${schema}DASHLOAD${org} (FIELD5)
;
CREATE BITMAP INDEX FIELD6_IDX ON ${schema}DASHLOAD${org} (FIELD6)
;
CREATE BITMAP INDEX FIELD7_IDX ON ${schema}DASHLOAD${org} (FIELD7)
;
CREATE BITMAP INDEX FIELD8_IDX ON ${schema}DASHLOAD${org} (FIELD8)
;
CREATE BITMAP INDEX FIELD9_IDX ON ${schema}DASHLOAD${org} (FIELD9)
;
