CREATE TABLE ${schema}C (
    Sel1 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel5 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel10 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel20 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel50 INTEGER WITH STORAGETYPE = COLUMNAR, 
    RowNUM INTEGER ${shardkey}
    )
;

CREATE TABLE ${schema}D (
    Sel1 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel5 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel10 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel20 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel50 INTEGER WITH STORAGETYPE = COLUMNAR, 
    RowNUM INTEGER ${shardkey}
    ) 
;