CREATE TABLE ${schema}C${org} (
    Sel1 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel5 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel10 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel20 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel50 INTEGER WITH STORAGETYPE = COLUMNAR, 
    RowNUM INTEGER ${shardkey}
    )
;

CREATE TABLE ${schema}D${org} (
    Sel1 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel5 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel10 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel20 INTEGER WITH STORAGETYPE = COLUMNAR, 
    Sel50 INTEGER WITH STORAGETYPE = COLUMNAR, 
    RowNUM INTEGER ${shardkey}
    ) 
;