CREATE BITMAP INDEX Sel1IDX ON TABLE C (Sel1)
;
CREATE BITMAP INDEX Sel5IDX ON TABLE C (Sel5)
;
CREATE BITMAP INDEX Sel10IDX ON TABLE C (Sel10)
;
CREATE BITMAP INDEX Sel20IDX ON TABLE C (Sel20)
;
CREATE BITMAP INDEX Sel50IDX ON TABLE C (Sel50)
;
CREATE BITMAP INDEX Sel1IDX ON TABLE D (Sel1)
;
CREATE BITMAP INDEX Sel5IDX ON TABLE D (Sel5)
;
CREATE BITMAP INDEX Sel10IDX ON TABLE D (Sel10)
;
CREATE BITMAP INDEX Sel20IDX ON TABLE D (Sel20)
;
CREATE BITMAP INDEX Sel50IDX ON TABLE D (Sel50)
;
