CREATE BITMAP INDEX Sel1IDX ON TABLE C${org} (Sel1)
;
CREATE BITMAP INDEX Sel5IDX ON TABLE C${org} (Sel5)
;
CREATE BITMAP INDEX Sel10IDX ON TABLE C${org} (Sel10)
;
CREATE BITMAP INDEX Sel20IDX ON TABLE C${org} (Sel20)
;
CREATE BITMAP INDEX Sel50IDX ON TABLE C${org} (Sel50)
;
CREATE BITMAP INDEX Sel1IDX ON TABLE D${org} (Sel1)
;
CREATE BITMAP INDEX Sel5IDX ON TABLE D${org} (Sel5)
;
CREATE BITMAP INDEX Sel10IDX ON TABLE D${org} (Sel10)
;
CREATE BITMAP INDEX Sel20IDX ON TABLE D${org} (Sel20)
;
CREATE BITMAP INDEX Sel50IDX ON TABLE D${org} (Sel50)
;
